In [2]:
import numpy as np

In [3]:
#slicing an array
y = np.arange(35).reshape(5,7)
print y
y[1:5:2,::3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[x<5]

array([0, 1, 2, 3, 4])

In [8]:
x[2:5]

array([2, 3, 4])

In [9]:
x[:-7]

array([0, 1, 2])

In [10]:
x[1:7:2]

array([1, 3, 5])